server:
  port: ${SERVICE_PORT:8082}
  address: ${SERVER_ADDRESS:0.0.0.0}
#  servlet:
#    context-path: ${CONTEXT_PATH:/auth}
  
spring:
  datasource:                  ## Datasource properties
    url: jdbc:mysql://localhost:3306/iam
    username: root
    password: root
  jpa:                  ## Hibernate properties
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
  mail:                 ## Mail properties
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS:paramsoft97@gmail.com}
    password: ${EMAIL_PASSWORD:xmsv krbi mzds xuyg}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      
management:
  endpoints:
    web:
      exposure:
        include: health,info
